export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCTS";
export const INCREASE_PRODUCT = "INCREASE_PRODUCTS";
export const DECREASE_PRODUCT = "DECREASE_PRODUCTS";
export const CLEAR_PRODUCT = "CLEAR_PRODUCTS";
